<?php

return [
    [
        'id'       => '0',
        'code'     => 'itemNo',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.itemNo',
        'type'     => 'text',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.itemNo',
    ],
    [
        'id'       => '1',
        'code'     => 'status',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.status',
        'type'     => 'boolean',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.status',
    ],
    [
        'id'       => '2',
        'code'     => 'name',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.name',
        'type'     => 'text',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.name',
    ],
    [
        'id'       => '3',
        'code'     => 'description',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.description',
        'type'     => 'textarea',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.description',
    ],
    [
        'id'       => '4',
        'code'     => 'gmtModified',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.gmtModified',
        'type'     => 'datetime',
        'required' => true,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.gmtModified',
    ], [
        'id'       => '5',
        'code'     => 'packWidth',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.packWidth',
        'type'     => 'text',
        'required' => true,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.packWidth',
    ], [
        'id'       => '6',
        'code'     => 'groupItemNo',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.groupItemNo',
        'type'     => 'text',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.groupItemNo',
    ], [
        'id'       => '7',
        'code'     => 'oem',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.oem',
        'type'     => 'boolean',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.oem',
    ], [
        'id'       => '8',
        'code'     => 'unitHeight',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.unitHeight',
        'type'     => 'text',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.unitHeight',
    ], [
        'id'       => '9',
        'code'     => 'modelLabel',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.modelLabel',
        'type'     => 'text',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.modelLabel',
    ], [
        'id'       => '10',
        'code'     => 'gmtListed',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.gmtListed',
        'type'     => 'datetime',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.gmtListed',
    ], [
        'id'       => '11',
        'code'     => 'packQty',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.packQty',
        'type'     => 'text',
        'required' => true,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.packQty',
    ], [
        'id'       => '12',
        'code'     => 'warehouse',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.warehouse',
        'type'     => 'text',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.warehouse',
    ], [
        'id'       => '13',
        'code'     => 'brandName',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.brandName',
        'type'     => 'text',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.brandName',
    ], [
        'id'       => '14',
        'code'     => 'id',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.id',
        'type'     => 'text',
        'required' => true,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.id',
    ], [
        'id'       => '15',
        'code'     => 'withLogo',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.withLogo',
        'type'     => 'boolean',
        'required' => true,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.withLogo',
    ], [
        'id'       => '16',
        'code'     => 'stock',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.stock',
        'type'     => 'text',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.stock',
    ], [
        'id'       => '17',
        'code'     => 'unitLength',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.unitLength',
        'type'     => 'text',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.unitLength',
    ], [
        'id'       => '18',
        'code'     => 'unitWidth',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.unitWidth',
        'type'     => 'text',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.unitWidth',
    ], [
        'id'       => '19',
        'code'     => 'picCount',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.picCount',
        'type'     => 'text',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.picCount',
    ], [
        'id'       => '20',
        'code'     => 'goodsType',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.goodsType',
        'type'     => 'text',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.goodsType',
    ], [
        'id'       => '22',
        'code'     => 'priceList',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.priceList',
        'type'     => 'price',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.priceList',
    ], [
        'id'       => '23',
        'code'     => 'barcode',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.barcode',
        'type'     => 'text',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.barcode',
    ], [
        'id'       => '24',
        'code'     => 'modelList',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.modelList',
        'type'     => 'text',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.modelList',
    ], [
        'id'       => '25',
        'code'     => 'moq',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.moq',
        'type'     => 'text',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.moq',
    ],  [
        'id'       => '26',
        'code'     => 'clearance',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.clearance',
        'type'     => 'boolean',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.clearance',
    ], [
        'id'       => '27',
        'code'     => 'leadTimeLevel',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.leadTimeLevel',
        'type'     => 'text',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.leadTimeLevel',
    ], [
        'id'       => '28',
        'code'     => 'packWeight',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.packWeight',
        'type'     => 'text',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.packWeight',
    ], [
        'id'       => '29',
        'code'     => 'price',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.price',
        'type'     => 'price',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.price',
    ], [
        'id'       => '30',
        'code'     => 'packLength',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.packLength',
        'type'     => 'text',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.packLength',
    ], [
        'id'       => '31',
        'code'     => 'baseImgCount',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.baseImgCount',
        'type'     => 'text',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.baseImgCount',
    ], [
        'id'       => '32',
        'code'     => 'unitWeight',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.unitWeight',
        'type'     => 'text',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.unitWeight',
    ], [
        'id'       => '33',
        'code'     => 'packHeight',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.packHeight',
        'type'     => 'text',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.packHeight',
    ], [
        'id'       => '34',
        'code'     => 'containsBattery',
        'name'     => 'sunsky_online::app.mappings.attribute.sunsky.containsBattery',
        'type'     => 'boolean',
        'required' => false,
        'title'    => 'sunsky_online::app.mappings.attribute.sunsky.containsBattery',
    ],
];
