<?php

return [
    [
        'id'       => '1',
        'code'     => 'sku',
        'name'     => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.attributes-name.sku',
        'type'     => 'text',
        'unique'   => true,
        'required' => true,
        'title'    => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.title.sku',
    ], [
        'id'       => '2',
        'code'     => 'name',
        'name'     => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.attributes-name.name',
        'type'     => 'text',
        'required' => true,
        'title'    => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.title.name',
    ], [
        'id'       => '3',
        'code'     => 'url_key',
        'name'     => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.attributes-name.url_key',
        'type'     => 'text',
        'required' => false,
        'title'    => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.title.url_key',
    ], [
        'id'       => '27',
        'code'     => 'product_number',
        'name'     => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.attributes-name.product_number',
        'type'     => 'text',
        'required' => false,
        'title'    => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.title.product_number',
    ], [
        'id'       => '7',
        'code'     => 'visible_individually',
        'name'     => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.attributes-name.visible_individually',
        'type'     => 'boolean',
        'required' => false,
        'title'    => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.title.visible_individually',
    ], [
        'id'       => '28',
        'code'     => 'manage_stock',
        'name'     => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.attributes-name.manage_stock',
        'type'     => 'boolean',
        'required' => false,
        'title'    => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.title.manage_stock',
    ], [
        'id'       => '25',
        'code'     => 'brand',
        'name'     => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.attributes-name.brand',
        'type'     => 'select',
        'required' => false,
        'title'    => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.title.brand',
    ], [
        'id'       => '11',
        'code'     => 'price',
        'name'     => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.attributes-name.price',
        'type'     => 'price',
        'required' => true,
        'title'    => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.title.price',
    ], [
        'id'       => '13',
        'code'     => 'special_price',
        'name'     => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.attributes-name.special_price',
        'type'     => 'price',
        'required' => false,
        'title'    => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.title.special_price',
    ], [
        'id'       => '12',
        'code'     => 'cost',
        'name'     => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.attributes-name.cost',
        'type'     => 'price',
        'required' => false,
        'title'    => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.title.cost',
    ], [
        'id'       => '9',
        'code'     => 'short_description',
        'name'     => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.attributes-name.short_description',
        'type'     => 'textarea',
        'required' => true,
        'title'    => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.title.short_description',
    ], [
        'id'       => '10',
        'code'     => 'description',
        'name'     => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.attributes-name.description',
        'type'     => 'textarea',
        'required' => true,
        'title'    => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.title.description',
    ], [
        'id'       => '16',
        'code'     => 'meta_title',
        'name'     => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.attributes-name.meta_title',
        'type'     => 'textarea',
        'required' => false,
        'title'    => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.title.meta_title',
    ], [
        'id'       => '17',
        'code'     => 'meta_keywords',
        'name'     => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.attributes-name.meta_keywords',
        'type'     => 'textarea',
        'required' => false,
        'title'    => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.title.meta_keywords',
    ], [
        'id'       => '18',
        'code'     => 'meta_description',
        'name'     => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.attributes-name.meta_description',
        'type'     => 'textarea',
        'required' => false,
        'title'    => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.title.meta_description',
    ], [
        'id'       => '19',
        'code'     => 'length',
        'name'     => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.attributes-name.length',
        'type'     => 'text',
        'required' => false,
        'title'    => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.title.length',
    ], [
        'id'       => '20',
        'code'     => 'width',
        'name'     => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.attributes-name.width',
        'type'     => 'text',
        'required' => false,
        'title'    => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.title.width',
    ], [
        'id'       => '21',
        'code'     => 'height',
        'name'     => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.attributes-name.height',
        'type'     => 'text',
        'required' => false,
        'title'    => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.title.height',
    ], [
        'id'       => '22',
        'code'     => 'weight',
        'name'     => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.attributes-name.weight',
        'type'     => 'text',
        'required' => false,
        'title'    => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.title.weight',
    ], [
        'id'       => '0',
        'code'     => 'images',
        'name'     => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.attributes-name.images',
        'type'     => 'gallery',
        'required' => false,
        'title'    => 'bagisto_plugin::app.bagisto-plugin.bagisto-attributes.title.images',
    ],
];
