<?php

return [
    'bagisto_categories' => [
        'title'    => 'bagisto_plugin::app.exporters.bagisto-plugin.category',
        'exporter' => 'Webkul\BagistoPlugin\Helpers\Exporters\Category\Exporter',
        'source'   => 'Webkul\Category\Repositories\CategoryRepository',
        'filters'  => [
            'fields' => [
                [
                    'name'       => 'credentials',
                    'title'      => 'bagisto_plugin::app.exporters.bagisto-plugin.credentials',
                    'required'   => true,
                    'validation' => 'required',
                    'type'       => 'select',
                    'async'      => true,
                    'track_by'   => 'id',
                    'label_by'   => 'shop_url',
                    'list_route' => 'bagisto.credential.fetch-all',
                ], [
                    'name'       => 'channel',
                    'title'      => 'bagisto_plugin::app.exporters.bagisto-plugin.channel',
                    'required'   => true,
                    'validation' => 'required',
                    'type'       => 'select',
                    'async'      => true,
                    'track_by'   => 'code',
                    'label_by'   => 'name',
                    'list_route' => 'bagisto.channel.fetch-all',
                ], [
                    'name'       => 'locale',
                    'title'      => 'bagisto_plugin::app.exporters.bagisto-plugin.locale',
                    'required'   => true,
                    'type'       => 'multiselect',
                    'validation' => 'required',
                    'async'      => true,
                    'track_by'   => 'code',
                    'label_by'   => 'name',
                    'list_route' => 'bagisto.locale.fetch-all',
                ], [
                    'name'     => 'code',
                    'title'    => 'bagisto_plugin::app.exporters.bagisto-plugin.code',
                    'required' => false,
                    'type'     => 'textarea',
                ],
            ],
        ],
    ],

    'bagisto_attribute' => [
        'title'    => 'bagisto_plugin::app.exporters.bagisto-plugin.attribute',
        'exporter' => 'Webkul\BagistoPlugin\Helpers\Exporters\Attribute\Exporter',
        'source'   => 'Webkul\Attribute\Repositories\AttributeRepository',
        'filters'  => [
            'fields' => [
                [
                    'name'       => 'credentials',
                    'title'      => 'bagisto_plugin::app.exporters.bagisto-plugin.credentials',
                    'required'   => true,
                    'validation' => 'required',
                    'type'       => 'select',
                    'async'      => true,
                    'track_by'   => 'id',
                    'label_by'   => 'shop_url',
                    'list_route' => 'bagisto.credential.fetch-all',
                ], [
                    'name'       => 'channel',
                    'title'      => 'bagisto_plugin::app.exporters.bagisto-plugin.channel',
                    'required'   => true,
                    'validation' => 'required',
                    'type'       => 'select',
                    'async'      => true,
                    'track_by'   => 'code',
                    'label_by'   => 'name',
                    'list_route' => 'bagisto.channel.fetch-all',
                ], [
                    'name'       => 'locale',
                    'title'      => 'bagisto_plugin::app.exporters.bagisto-plugin.locale',
                    'required'   => true,
                    'type'       => 'multiselect',
                    'validation' => 'required',
                    'async'      => true,
                    'track_by'   => 'code',
                    'label_by'   => 'name',
                    'list_route' => 'bagisto.locale.fetch-all',
                ], [
                    'name'     => 'code',
                    'title'    => 'bagisto_plugin::app.exporters.bagisto-plugin.code',
                    'required' => false,
                    'type'     => 'textarea',
                ],
            ],
        ],
    ],

    'bagisto_attribute_families' => [
        'title'    => 'bagisto_plugin::app.exporters.bagisto-plugin.attribute-families',
        'exporter' => 'Webkul\BagistoPlugin\Helpers\Exporters\AttributeFamily\Exporter',
        'source'   => 'Webkul\Attribute\Repositories\AttributeFamilyRepository',
        'filters'  => [
            'fields' => [
                [
                    'name'       => 'credentials',
                    'title'      => 'bagisto_plugin::app.exporters.bagisto-plugin.credentials',
                    'required'   => true,
                    'validation' => 'required',
                    'type'       => 'select',
                    'async'      => true,
                    'track_by'   => 'id',
                    'label_by'   => 'shop_url',
                    'list_route' => 'bagisto.credential.fetch-all',
                ], [
                    'name'       => 'channel',
                    'title'      => 'bagisto_plugin::app.exporters.bagisto-plugin.channel',
                    'required'   => true,
                    'validation' => 'required',
                    'type'       => 'select',
                    'async'      => true,
                    'track_by'   => 'code',
                    'label_by'   => 'name',
                    'list_route' => 'bagisto.channel.fetch-all',
                ], [
                    'name'       => 'locale',
                    'title'      => 'bagisto_plugin::app.exporters.bagisto-plugin.locale',
                    'required'   => true,
                    'type'       => 'multiselect',
                    'validation' => 'required',
                    'async'      => true,
                    'track_by'   => 'code',
                    'label_by'   => 'name',
                    'list_route' => 'bagisto.locale.fetch-all',
                ], [
                    'name'     => 'code',
                    'title'    => 'bagisto_plugin::app.exporters.bagisto-plugin.code',
                    'required' => false,
                    'type'     => 'textarea',
                ],
            ],
        ],
    ],

    'bagisto_product' => [
        'title'    => 'bagisto_plugin::app.exporters.bagisto-plugin.product',
        'exporter' => 'Webkul\BagistoPlugin\Helpers\Exporters\Product\Exporter',
        'source'   => 'Webkul\Product\Repositories\ProductRepository',
        'filters'  => [
            'fields' => [
                [
                    'name'       => 'credentials',
                    'title'      => 'bagisto_plugin::app.exporters.bagisto-plugin.credentials',
                    'required'   => true,
                    'validation' => 'required',
                    'type'       => 'select',
                    'async'      => true,
                    'track_by'   => 'id',
                    'label_by'   => 'shop_url',
                    'list_route' => 'bagisto.credential.fetch-all',
                ], [
                    'name'       => 'channel',
                    'title'      => 'bagisto_plugin::app.exporters.bagisto-plugin.channel',
                    'required'   => true,
                    'validation' => 'required',
                    'type'       => 'multiselect',
                    'async'      => true,
                    'track_by'   => 'code',
                    'label_by'   => 'name',
                    'list_route' => 'bagisto.channel.fetch-all',
                ], [
                    'name'       => 'locale',
                    'title'      => 'bagisto_plugin::app.exporters.bagisto-plugin.locale',
                    'required'   => true,
                    'type'       => 'multiselect',
                    'validation' => 'required',
                    'async'      => true,
                    'track_by'   => 'code',
                    'label_by'   => 'name',
                    'list_route' => 'bagisto.locale.fetch-all',
                ], [
                    'name'     => 'with_media',
                    'title'    => 'bagisto_plugin::app.exporters.bagisto-plugin.with_media',
                    'required' => false,
                    'type'     => 'boolean',
                ], [
                    'name'     => 'sku',
                    'title'    => 'bagisto_plugin::app.exporters.bagisto-plugin.sku',
                    'required' => false,
                    'type'     => 'textarea',
                ],
            ],
        ],
    ],
];
