name: Linting Tests

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  linting_tests:
    runs-on: ubuntu-24.04
    name: Laravel Pint Code Style

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2

      - name: Install Pint
        run: composer global require laravel/pint --no-progress --dev

      - name: Add Composer Global Bin to PATH
        run: echo "$HOME/.config/composer/vendor/bin" >> $GITHUB_PATH

      - name: Running Pint Test
        run: pint --test -v
